### ISSUE TITLE
Could not find wasm-opt to optimise the module

### ISSUE THREAD

**Issue by dylanh724** [MrRefactoring/wasm-opt#22]
When using this:

https://github.com/WebAssembly/binaryen/releases

it can't find `wasm-opt`, although it's in PATH. Any ideas?

**Comment by MrRefactoring** [comment]
Hi @dylanh724,

Thank you for bringing up this issue. I want to clarify that my contribution to this project is specifically focused on integrating wasm-opt directly into the repository at the time the package is installed. This approach ensures that wasm-opt is readily available and configured correctly as part of the installation process, enhancing usability and streamlining setup for all users.

Please note that while I understand there might be other potential solutions or broader considerations for integrating wasm-opt, my involvement is limited to this particular aspect of the project. Other approaches or configurations might require separate discussions or contributions from other developers.

Let me know if there's anything specific regarding the local integration of wasm-opt that you'd like to discuss or refine further.

Best regards,
Vladislav

**Comment by dylanh724** [comment]
I'll close this since I don't have much more to offer from here -- but if someone else stumbles across this with more info, feel free to reopen
