### ISSUE TITLE
(node:24846) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied

### ISSUE THREAD

**Issue by JHBonarius** [MrRefactoring/wasm-opt#6]
I'm trying to install wasm-opt on my raspberry pie 3b via npm, but it fails with an exception.

`[...]@~$sudo npm i wasm-opt -g
[sudo] password for [...]:
/usr/bin/wasm-opt -> /usr/lib/node_modules/wasm-opt/out/wasm-opt.js

> wasm-opt@1.1.1 postinstall /usr/lib/node_modules/wasm-opt
> node ./out/index.js

✔ Release success found
✔ Binaries successfully downloaded
(node:24846) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, open 'binaryen-1.39.1.tar.gz'
    at Object.openSync (fs.js:465:3)
    at Object.writeFileSync (fs.js:1416:35)
    at /usr/lib/node_modules/wasm-opt/out/index.js:89:20
    at step (/usr/lib/node_modules/wasm-opt/out/index.js:33:23)
    at Object.next (/usr/lib/node_modules/wasm-opt/out/index.js:14:53)
    at fulfilled (/usr/lib/node_modules/wasm-opt/out/index.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:24846) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24846) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
+ wasm-opt@1.1.1
updated 2 packages in 16.372s`

**Comment by MrRefactoring** [comment]
On which operating system are you trying to do this? MacOs or Linux?

**Comment by JHBonarius** [comment]
Linux (Raspbian GNU/Linux 10 (buster))

**Comment by MrRefactoring** [comment]
Okay, I will try to reproduce this at my place. You can try to install version 1.39.1-beta.2. https://www.npmjs.com/package/wasm-opt/v/1.39.1-beta.2.

Thanks

**Comment by JHBonarius** [comment]
`[...]@~$npm i wasm-opt@1sudo .39.1-beta.2 -g
[sudo] password for [...]:
/usr/bin/wasm-opt -> /usr/lib/node_modules/wasm-opt/bin/wasm-opt.js

> wasm-opt@1.39.1-beta.2 postinstall /usr/lib/node_modules/wasm-opt
> node bin/index.js

This platform not supported
+ wasm-opt@1.39.1-beta.2
removed 30 packages and updated 4 packages in 8.138s`

**Comment by MrRefactoring** [comment]
Oh. Thats not good)

**Comment by MrRefactoring** [comment]
Please check 1.2.0 version
